image:
  repository: your-dockerhub/laravel-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  APP_ENV: production
  DB_HOST: mysql
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: laravel
